### ISSUE TITLE
NPM install fails (Linux)

### ISSUE THREAD

**Issue by maxbartunik** [PagerBuddy/Server#86]
A user reports an error attempting to npm install on a linux system. Log:

npm ERR! code 1
npm ERR! path /usr/bin/pagerbuddy/Server/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c -- node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.12.1 | linux | arm64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/bin/pagerbuddy/Server/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/bin/pagerbuddy/Server/node_modules/bufferutil/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/bin/pagerbuddy/Server/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.12.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.12.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/bin/pagerbuddy/Server/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.12.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/bin/pagerbuddy/Server/node_modules/bufferutil',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/bin/pagerbuddy/Server/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/bin/pagerbuddy/Server/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/bin/pagerbuddy/Server/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/bin/pagerbuddy/Server/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/bin/pagerbuddy/Server/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/bin/pagerbuddy/Server/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/bin/pagerbuddy/Server/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/bin/pagerbuddy/Server/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp ERR! System Linux 5.4.0-1077-raspi
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/bin/pagerbuddy/Server/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /usr/bin/pagerbuddy/Server/node_modules/bufferutil
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by maxbartunik** [comment]
I believe this is Ubuntu-specific, with a potential solution here: https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error

**Comment by maxbartunik** [comment]
Was fixed with the above solution. Perhaps we can include a warning in the installer?
